<?php
?>
<h1>Willkommen auf Silas.link</h1>
<br/>
<p>Hallo und Herzlich willkommen auf Silas.link. Diese Seite befindet sich momentan noch im Aufbau.
	Von daher sieht es hier noch nicht so perfekt aus. Und viel Machen kann man auch noch nicht wirklich.
	Wozu gibt es die Seite dann überhaupt? Eigentlich erstmal nur für mich. Ich mag es zu programmieren und diese
	Seite habe ich selbstständig programmiert. Genutzt habe ich dazu PHP und Javascript. Oh und natürlich Zend Framework 2
	und JQuery.
	<br/>Okay, was du machen kannst ist dich anmelden. Und wenn ich den Text hier aktuell halte sonst noch nichts. Aber
	wahrscheinlicher ist es, dass ich den Text hier nur geschrieben habe, weil mir etwas langweilig war und ich nichts
	besseres zu tun hatte. Und deswegen wird er auch nicht unbedingt aktuell gehalten. Von daher kann es durchaus sein,
	dass es schon längst neue Features gibt, die nur darauf warten von dir entdeckt zu werden...
	<br/><br/>Viel Spaß
</p>