<?php
	$this->headLink()->prependStylesheet($this->basepath() . '/css/index.css');
?>
<div class="orbit distanceAbove" role="region" aria-label="Home Header" data-orbit>
	<ul class="orbit-container">
		<button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
		<button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
		<li class="is-active orbit-slide">
			<img class="orbit-image" src="../sliderImg/Slider1.png" alt="Werbung">
		</li>
		<li class="orbit-slide">
			<img class="orbit-image" src="../sliderImg/slider2.png" alt="Rad im Kornfeld">
		</li>
		<li class="orbit-slide">
			<img class="orbit-image" src="../sliderImg/slider3.png" alt="Radrennen">
		</li>
	</ul>
	<nav class="orbit-bullets">
		<button class="is-active" data-slide="0"><span class="show-for-sr">First slide details.</span><span class="show-for-sr">Current Slide</span></button>
		<button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
		<button data-slide="2"><span class="show-for-sr">Third slide details.</span></button>
	</nav>
</div>
<div class="textAlign">
	<h1>Willkommen in unseren Online Shop</h1>
	<p>
		Hier finden Sie ein großes Angebot an verschiedensten Fahrräder und Zubehör für Ihre Fahrräder.
	</p>
	<b><a href="<?php echo $this->url("bikelist"); ?>">zu den Fahrrädern</a><br></b>
	<b><a href="<?php echo $this->url("Bikepart");?>">zum Zubehör</a></b>
</div>
<?php
    echo $this->inlineScript()->appendFile($this->basePath('js/app.js'));
?>
