<h1>Impressum</h1>
<h2>Angaben gemäß § 5 TMG:</h2>
<p>puzzles GmbH & CO. KG<br />
	ABC Straße 123<br />
	01234 ABC Stadt
</p>
<h2>Vertreten durch:</h2>
<p>M. Schulz</p>
<h2>Kontakt:</h2>
<table><tr>
		<td>Telefon:</td>
		<td></td></tr>
	<tr><td>E-Mail:</td>
		<td>schulzm.tinf14@student.dhbw-heidenheim.de</td>
	</tr></table>
<h2>Hinweis auf EU-Streitschlichtung</h2>
<p>Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit: <a href="http://ec.europa.eu/consumers/odr">http://ec.europa.eu/consumers/odr</a><br /> Unsere E-Mail-Adresse finden sie oben im Impressum. <p> </p>
<p> </p>
<p>Quelle: <em><a href="https://www.e-recht24.de/impressum-generator.html">https://www.e-recht24.de</a></em></p>