<?php
/**
 * Created by PhpStorm.
 * User: silas
 * Date: 14.06.16
 * Time: 16:19
 */

namespace BikeStore\Form\Hydrator;


class BicycleFilterHydrator extends ArticleFilterHydrator
{
	public function extract($object)
	{
		return parent::extract($object); // TODO: Change the autogenerated stub
	}

	public function hydrate(array $data, $bikePartFilterContainer)
	{
		return parent::hydrate($data, $bikePartFilterContainer); // TODO: Change the autogenerated stub
	}
}