<?php
/**
 * Created by PhpStorm.
 * User: Kinomi
 * Date: 31.05.2016
 * Time: 17:57
 */
/** @var \BikeStore\Model\Bicycle $article */
$this->inlineScript()->captureStart();
echo <<<JS
	$(document).ready(function(){
			$("#tabs").tabs({
			});
	});
JS;

$this->inlineScript()->captureEnd();
?>

<h1>Produktinformationen</h1>
<div id="tabs">
	<ul class="productInfoBackground">
		<li ><a href="#tabs-1" >Beschreibung</a></li>
		<li><a href="#tabs-2">Übersicht</a></li>
	</ul>
	<div id="tabs-1">
		<p>
			<?php
				echo $this->escapeHtml($article->getDescription())?>
		</p>
	</div>
	<div id="tabs-2">
		<table>
			<tr><td>Name:</td><td><?php
					echo $this->escapeHtml($article->getName());
					?></td></tr>
			<tr><td>Typ:</td><td><?php
					$type = $this->escapeHtml($article->getFrame()->getBikeType());
					echo \BikeStore\Model\Manager\Equipment\FrameManager::resolveBikeType($type);
					?></td></tr>
			<tr><td>Kategory:</td><td><?php
					$type = $this->escapeHtml($article->getFrame()->getRiderType());
					echo \BikeStore\Model\Manager\Equipment\FrameManager::resolveRideType($type);
					?></td></tr>
			<tr><td>Radgröße:</td><td><?php
					echo $this->escapeHtml($article->getFrontWheel()->getSize());
					?> "</td></tr>
			<tr><td>Rahmengröße:</td><td><?php
					echo $this->escapeHtml($article->getFrame()->getFrameSize());
					?> "</td></tr>
			<tr><td>Farbe:</td><td><?php
					echo $this->escapeHtml($article->getFrame()->getColor());
					?></td></tr>
			<tr><td>Satteltyp:</td><td><?php
					$type = $this->escapeHtml($article->getSaddle()->getType());
					echo \BikeStore\Model\Manager\Equipment\SaddleManager::resolveSaddleType($type);
					?></td></tr>
			<tr><td>Sattelmaterial:</td>
				<td><?php
					$type = $this->escapeHtml($article->getSaddle()->getMaterial());
					echo \BikeStore\Model\Manager\Equipment\SaddleManager::resolveSaddleMaterial($type);
					?>
				</td></tr>
			<tr><td>Vorderrad Bremse:</td><td><?php
					echo $this->escapeHtml($article->getFrontBrake()->getName());
					?></td></tr>
			<tr><td>Hinterrad Bremse:</td><td><?php
					echo $this->escapeHtml($article->getRearBrake()->getName());
					?></td></tr>
			<tr><td>Lenkerhöhe:</td><td><?php
					echo $this->escapeHtml(number_format($article->getHandlebars()->getLength(), 2, ",", "."));
					?> cm</td></tr>
			<tr><td>Sattelhöhe:</td><td><?php
					echo $this->escapeHtml(number_format($article->getSaddleBar()->getLength(), 2, ",", "." ));
					?> cm</td></tr>
		</table>
	</div>
</div>

