<?php
/**
 * Created by PhpStorm.
 * User: Kinomi
 * Date: 31.05.2016
 * Time: 17:57
 */
/** @var \BikeStore\Model\Bicycle $article */
$this->inlineScript()->captureStart();
echo <<<JS
	$(document).ready(function(){
			$("#tabs").tabs({
				
			});
	});
JS;

$this->inlineScript()->captureEnd();
?>

<h1>Produktinformationen</h1>
<div id="tabs">
	<ul class="productInfoBackground">
		<li ><a href="#tabs-1" >Beschreibung</a></li>
		<li><a href="#tabs-2">Übersicht</a></li>
	</ul>
	<div id="tabs-1">
		<p>
			<?php
				echo $this->escapeHtml($article->getDescription())?>
		</p>
	</div>
	<div id="tabs-2">
		<table>
			<tr><td>Name:</td><td><?php
					echo $this->escapeHtml($article->getName());
					?></td></tr>
			<tr><td>Typ:</td><td><?php
					$type = $this->escapeHtml($article->getFrame()->getBikeType());
					if($type = 1){
						echo "City Fahrrad";
					}
					else if($type = 2){
						echo "Mountainbike";
					}
					else if($type = 3){
						echo "Rennrad";
					}
					else if($type = 4){
						echo "Touring Fahrrad";
					}
					else if($type = 5){
						echo "Elektro Fahrrad";
					}
					else{
						echo "Type nicht gefunden!";
					}
					?></td></tr>
			<tr><td>Radgröße:</td><td><?php
					echo $this->escapeHtml($article->getFrontWheel()->getSize());
					?> "</td></tr>
			<tr><td>Rahmengröße:</td><td><?php
					echo $this->escapeHtml($article->getFrame()->getFrameSize());
					?> "</td></tr>
			<tr><td>Farbe:</td><td><?php
					echo $this->escapeHtml($article->getFrame()->getColor());
					?></td></tr>
			<tr><td>Sattelart:</td><td><?php
					echo "gibts noch nicht";
					?></td></tr>
			<tr><td>Bremspaket:</td><td><?php
					echo "gibts auch noch nicht!"
					?></td></tr>
			<tr><td>Lenkerhöhe:</td><td><?php
					echo "fehlt";
					?></td></tr>
			<tr><td>Sattelhöhe:</td><td><?php
					echo $this->escapeHtml(number_format($article->getSaddleBar()->getLength(), 2, ",", "." ));
					?> cm</td></tr>
		</table>
	</div>
</div>

