<?php
/**
 * Created by PhpStorm.
 * User: Kinomi
 * Date: 31.05.2016
 * Time: 17:57
 */
/** @var \BikeStore\Model\Article $article */
$this->inlineScript()->captureStart();
echo <<<JS
	$(document).ready(function(){
			$("#tabs").tabs({
				event: "mouseover"
			});
	});
JS;

$this->inlineScript()->captureEnd();
?>

<h1>Produktinformationen</h1>
<div id="tabs">
	<ul class="productInfoBackground">
		<li ><a href="#tabs-1" >Beschreibung</a></li>
		<li><a href="#tabs-2">Übersicht</a></li>
	</ul>
	<div id="tabs-1">
		<p>
			<?php
				echo $article->getDescription()?>
		</p>
	</div>
	<div id="tabs-2">
		<p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante, ut pharetra massa metus id nunc. Duis scelerisque molestie turpis. Sed fringilla, massa eget luctus malesuada, metus eros molestie lectus, ut tempus eros massa ut dolor. Aenean aliquet fringilla sem. Suspendisse sed ligula in ligula suscipit aliquam. Praesent in eros vestibulum mi adipiscing adipiscing. Morbi facilisis. Curabitur ornare consequat nunc. Aenean vel metus. Ut posuere viverra nulla. Aliquam erat volutpat. Pellentesque convallis. Maecenas feugiat, tellus pellentesque pretium posuere, felis lorem euismod felis, eu ornare leo nisi vel felis. Mauris consectetur tortor et purus.</p>
	</div>
</div>

