<?php
/**
 * Created by PhpStorm.
 * User: Kinomi
 * Date: 31.05.2016
 * Time: 17:57
 */
/** @var \BikeStore\Model\Bicycle $article */
$this->inlineScript()->captureStart();
echo <<<JS
	$(document).ready(function(){
			$("#tabs").tabs({
			});
	});
JS;

$this->inlineScript()->captureEnd();
?>

<h1>Produktinformationen</h1>
<div id="tabs">
	<ul class="productInfoBackground">
		<li><a href="#tabs-1">Beschreibung</a></li>
		<li><a href="#tabs-2">Übersicht</a></li>
	</ul>
	<div id="tabs-1">
		<p>
			<?php
			echo $this->escapeHtml($article->getDescription()) ?>
		</p>
	</div>
	<div id="tabs-2">
		<table>
			<?php
			foreach ($this->article->getViewInformationAsArray() as $viewName => $viewAttribute)
			{
				if (is_array($viewAttribute))
				{
					echo "<tr><td>".$viewAttribute["label"]."</td><td ".((isset($viewAttribute["id"]))?" id = \"".$viewAttribute["id"]."\" ":"").">".$viewAttribute["value"]."</td></tr>";
				}
				else
				{
					echo "<tr><td>" . $this->escapeHtml($viewName) . ":</td><td>" . $this->escapeHtml($viewAttribute) .
						 "</td></tr>";
				}
			}
			?>
		</table>
	</div>
</div>

