<?php
/**
 * Created by PhpStorm.
 * User: DaDobe
 * Date: 07.06.2016
 * Time: 11:36
 */
$this->headLink()->prependStylesheet($this->basePath() . '/css/boxedLayoutAnzeige.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bikePart.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bikePart.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/boxedLayoutAnzeige.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/filterForm.css');

$this->headScript()->appendFile($this->basePath() . '/js/bikePartView.js');
$this->headScript()->appendFile($this->basePath() . '/js/pageNavigator.js');
$this->headScript()->appendFile($this->basePath() . '/js/FilterForm.js');


echo "<h1>Suchergebnisse</h1>";
$alleElemente = array();
foreach ($this->result as $Eqipment)
{
	$element = (\BikeStore\Model\Manager\EquipmentManager::getAsArray($Eqipment));;
	$element["url"] = $this->url('articleDetails', array('id' => $Eqipment->getId()));
	$alleElemente[] = $element;
}
$ElementArray = json_encode($alleElemente);
echo "<button id='list '  class='bikeShopDefaultBtn' type='button' onclick='elementRender.createList()'>";
include(realpath('public/image/list.svg'));
echo "</button>";
echo "<button id='list '  class='bikeShopDefaultBtn' type='button' onclick='elementRender.createBox()'>";
include(realpath('public/image/box.svg'));
echo "</button>";

$urlBicycleListLink = $this->url("bikelist");
$urlEquipmentListLink = $this->url("Bikepart");
$this->inlineScript()->captureStart();
echo <<<JS
	$(document).ready(function() {
		pageNavigator.actualPage = $this->page;
		pageNavigator.maxPage = $this->maxPage;
		
		elementRender.BikeList = false;
	  	elementRender.addArrayElements($ElementArray);
	  	elementRender.init();
	  	elementRender.render();
	  	FilterForm.setForm($("#articleFilterForm"));
	  
	  	$(document).ready(function(){
			$("#buttonBicycle").click(function(){
				$("#articleFilterForm").attr("action", "$urlBicycleListLink");
				FilterForm.sendForm();
			});	
			$("#buttonBikePart").click(function(){
				$("#articleFilterForm").attr("action", "$urlEquipmentListLink");
				FilterForm.sendForm();
			})	
	  	});
	})
JS;
$this->inlineScript()->captureEnd();

echo "<div class='row'>";
echo "<div class='columns small-2'>";
$this->filterForm->setAttribute("action", $this->url("search"));
$this->filterForm->prepare();
echo $this->form()->openTag($this->filterForm);
echo $this->formHidden($this->filterForm->get("search"));
echo $this->formHidden($this->filterForm->get("page"));
?>

<div id='bikePartFormPrice'>
	<br/>
	<h4>Suche eingrenzen:</h4>
	<a class="btn-link" id="buttonBicycle">Fahrräder</a>
	<br/>
	<a class="btn-link" id="buttonBikePart">Zubehör</a> <br/>
	Preis:
	<div class = "row">
		<?php
		echo "<div class = 'columns large-5 small-5'>" . $this->formRow($this->filterForm->get("priceMin")) .
			 "</div>";
		echo "<div class = 'columns large-5 small-5'>" . $this->formRow($this->filterForm->get("priceMax")) .
			 "</div>";
		echo "<div class = 'columns large-2 small-2'>" .
			 $this->formRow($this->filterForm->get("smallSubmitButton")) . "</div>";
		?>
	</div>
</div>
<?php
echo $this->form()->closeTag();
echo "</div>";
?>
<div class="columns large-10"><p id='AusgabePanel'></p></div>
</div>