<?php
/**
 * Created by PhpStorm.
 * User: DaDobe
 * Date: 07.06.2016
 * Time: 11:36
 */
$this->headLink()->prependStylesheet($this->basePath() . '/css/boxedLayoutAnzeige.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bikePart.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bikePart.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/boxedLayoutAnzeige.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/filterForm.css');

$this->headScript()->appendFile($this->basePath() . '/js/bikePartView.js');
$this->headScript()->appendFile($this->basePath() . '/js/pageNavigator.js');
$this->headScript()->appendFile($this->basePath() . '/js/FilterForm.js');


echo "<h1>Suchergebnisse</h1>";
$maxPrice = 0;
$alleElemente = array();
foreach ($this->result as $Eqipment)
{
	$element = (\BikeStore\Model\Manager\EquipmentManager::getAsArray($Eqipment));;
	$element["url"] = $this->url('articleDetails', array('id' => $Eqipment->getId()));
	$alleElemente[] = $element;
	$maxPrice = max($maxPrice, $element["price"]);
}
$ElementArray = json_encode($alleElemente);

$urlBicycleListLink = $this->url("bikelist");
$urlEquipmentListLink = $this->url("Bikepart");
$this->inlineScript()->captureStart();
echo <<<JS
	$(document).ready(function() {
		pageNavigator.actualPage = $this->page;
		pageNavigator.maxPage = $this->maxPage;
		
		elementRender.BikeList = false;
	  	elementRender.addArrayElements($ElementArray);
	  	elementRender.init();
	  	elementRender.render();
	  	FilterForm.setForm($("#articleFilterForm"));
	  	
	  	setFilterRanges({
	  		minPrice: 0,
	  		maxPrice: $maxPrice
	  	});
	  
	  	$(document).ready(function(){
			$("#buttonBicycle").click(function(){
				$("#articleFilterForm").attr("action", "$urlBicycleListLink");
				FilterForm.sendForm();
			});	
			$("#buttonBikePart").click(function(){
				$("#articleFilterForm").attr("action", "$urlEquipmentListLink");
				FilterForm.sendForm();
			})	
	  	});
	})
	
	function setFilterRanges(settings) {
		var jq_minPrice = $('input[name=priceMin]'),
			jq_maxPrice = $('input[name=priceMax]'),
			jq_minFrameHeight = $('input[name=frameHeightMin]'),
			jq_maxFrameHeight = $('input[name=frameHeightMax]');
		
		if(!jq_minPrice.val())
			jq_minPrice.val(settings.minPrice).attr('min', settings.minPrice).attr('max', settings.maxPrice);
		
		if(!jq_maxPrice.val())
			jq_maxPrice.val(settings.maxPrice).attr('min', settings.minPrice).attr('max', settings.maxPrice);
	}
JS;
$this->inlineScript()->captureEnd();

echo "<div class='row'>";
echo "<div class='columns small-5 medium-3 large-2'>";
$this->filterForm->setAttribute("action", $this->url("search"));
$this->filterForm->prepare();

echo "<button id='list '  class='bikeShopDefaultBtn' type='button' onclick='elementRender.createList()' title='Listenansicht'>";
include(realpath('public/image/list.svg'));
echo "</button>";
echo "<button id='list '  class='bikeShopDefaultBtn' type='button' onclick='elementRender.createBox()' title='Kachelansicht'>";
include(realpath('public/image/box.svg'));
echo "</button>";

echo $this->form()->openTag($this->filterForm);
echo $this->formHidden($this->filterForm->get("search"));
echo $this->formHidden($this->filterForm->get("page"));
?>

<div id='bikePartFormPrice'>
	<h4>Filter</h4>
	<a class="btn-link" id="buttonBicycle">Fahrräder</a>
	<br/>
	<a class="btn-link" id="buttonBikePart">Zubehör</a> <br/>
	<h4>Preis</h4>
	<div class = "row">
		<?php
		echo "<div class = 'columns large-5 small-5'>" . $this->formRow($this->filterForm->get("priceMin")) .
			 "</div>";
		echo "<div class = 'columns large-5 small-5'>" . $this->formRow($this->filterForm->get("priceMax")) .
			 "</div>";
		echo "<div class = 'columns large-2 small-2'>" .
			 $this->formRow($this->filterForm->get("smallSubmitButton")) . "</div>";
		?>
	</div>
</div>
<?php
echo $this->form()->closeTag();
echo "</div>";
?>
<div class="columns"><p id='AusgabePanel'></p></div>
</div>