<?php
/**
 * Created by PhpStorm.
 * User: Kinomi
 * Date: 28.05.2016
 * Time: 23:15
 */
$this->headLink()->prependStylesheet($this->basepath() . '/css/detailContent.css');
$this->headScript()->appendFile($this->basePath() . '/js/customizer.js');

/** @var \BikeStore\Model\Article $article */
$isBicycle = ($article instanceof \BikeStore\Model\Bicycle);
$isBicycleJs = ($isBicycle) ? "true" : "false";

$brakesFrontJson = "";
$brakesRearJson = "";
$saddleJson = "";
$currentBrakeFrontId = 0;
$currentBrakeRearId = 0;
$currentBrakeFrontPrice = 0;
$currentBrakeRearPrice = 0;
$currentSaddlePrice = 0;
$currentSaddleId = 0;
if($isBicycle)
{
	/** @var \BikeStore\Model\Bicycle $article */
	$currentBrakeFrontPrice = $article->getFrontBrake()->getPrice();
	$currentBrakeFrontId = $article->getFrontBrake()->getId();
	$brakeArray = array();
	/** @var \BikeStore\Model\Equipment\Brake $brake */
	foreach($this->possibleBrakesFront as $brake)
	{
		$brakeArray[] = \BikeStore\Model\Manager\Equipment\BrakeManager::getAsArray($brake);
	}
	$brakesFrontJson = json_encode($brakeArray);

	$currentBrakeRearPrice = $article->getRearBrake()->getPrice();
	$currentBrakeRearId = $article->getRearBrake()->getId();
	$brakeArray = array();
	/** @var \BikeStore\Model\Equipment\Brake $brake */
	foreach($this->possibleBrakesRear as $brake)
	{
		$brakeArray[] = \BikeStore\Model\Manager\Equipment\BrakeManager::getAsArray($brake);
	}
	$brakesRearJson = json_encode($brakeArray);

	$currentSaddlePrice = $article->getSaddle()->getPrice();
	$currentSaddleId = $article->getSaddle()->getId();
	$saddleArray = array();
	/** @var \BikeStore\Model\Equipment\Saddle $saddle */
	foreach($this->possibleSaddles as $saddle)
	{
		$saddleArray[] = \BikeStore\Model\Manager\Equipment\SaddleManager::getAsArray($saddle);
	}
	$saddleJson = json_encode($saddleArray);
}

$url = $this->url("addToCart");
$id = $article->getId();
$name = $article->getName();
$price = $article->getPrice();
$this->inlineScript()->captureStart();
echo <<<JS
		$(document).ready(function() {
		  	$("#shoppingCartBtn").click(function(){
		  		var count = parseInt($("#mengenListe").val());
		  		var postValues = {
		  			id: $id,
		  			count: count
		  		}
		  		if ($isBicycleJs)
		  		{
					postValues = $.extend(postValues, customizer.getSelectValues());		  		
		  			console.log(postValues);
		  		}
		  		$.post("$url", postValues, function(data) {
		  		  if(data['success'] === true)
		  		  {
		  		  		$('.myMainContainerWrapper').animate({scrollTop: 0}, 800);
		  		  		numberArticlesInShoppingCart += count;
						flashMessenger.addMessage(flashMessenger.messageTypeSuccess, "$name wurde dem Warenkorb hinzugefügt");
						$(".warenkorbText").first().html(numberArticlesInShoppingCart + ' Artikel <br> im Warenkorb');
		  		  }
		  		}, "json").fail(function() 
		  		{
		  		  flashMessenger.addMessage(flashMessenger.messageTypeError, "Ein Fehler ist aufgetreten, $name konnte nicht dem Warenkorb hinzugefügt werden!");
		  		});
		  	});
		  	if ($isBicycleJs)
		  	{
		  		customizer.setBicyclePrice($price);
		  	
				customizer.addManyOptions("selectBrakeFront", $brakesFrontJson);		  	
				customizer.addManyOptions("selectBrakeRear", $brakesRearJson);		  	
				customizer.addManyOptions("selectSaddle", $saddleJson);	
					  	
				customizer.setCurrentId("selectBrakeFront", $currentBrakeFrontId);
				customizer.setCurrentId("selectBrakeRear", $currentBrakeRearId);
				customizer.setCurrentId("selectSaddle", $currentSaddleId);
		  		customizer.init();
		  		
				// customizer.bicyclePrice = $price;
//				customizer.currentBrakeFrontPrice = $currentBrakeFrontPrice;
//				customizer.currentBrakeRearPrice = $currentBrakeRearPrice;
//				customizer.currentSaddlePrice = $currentSaddlePrice;
//				
//				customizer.addManyBrakesFront($brakesFrontJson);			
//				customizer.addManyBrakesRear($brakesRearJson);	
//				customizer.setCurrentFrontBrake($currentBrakeFrontId);
//				customizer.setCurrentRearBrake($currentBrakeRearId);
//				customizer.addOptionsToSelectBox();
//				customizer.init();
		  	}
		 })
JS;
$this->inlineScript()->captureEnd();

?>
<div class="detailContent flexHeader">
	<div class="detailPicture flexFillWidth">
		<h1><?php
			echo $this->escapeHtml($article->getName());
			?>
		</h1>
		<img src="/image/<?php echo $this->escapeHtml($article->getImageName())
		?>"/>
	</div>
	<div id="detailBuy">
		<!--		<p>-->
		<div id='priceTable' class='table'>
			<div class='row'>
				<span class='priceTableCellLeft cell'><?php if($isBicycle)
					{
						echo "Fahrrad:";
					} ?></span>
				<span class='<?php if($isBicycle)
				{
					echo "priceTableCellRight ";
				} ?> cell'><?php echo $this->price($article->getPrice(), $isBicycle) ?></span>
			</div>
			<?php if($isBicycle)
			{
				?>
				<div class="row">
					<label class='priceTableCellLeft cell' for="selectSaddle">Sattel:</label>
					<select id="selectSaddle" class="form-control priceTableCellRight cell customizingSelectBox"></select>
				</div>
				<div class="row">
					<label class='priceTableCellLeft cell' for="selectBrakeFront">Vorderbremse:</label>
					<select id="selectBrakeFront" class="form-control priceTableCellRight cell customizingSelectBox"></select>
				</div>
				<div class="row">
					<label class='priceTableCellLeft cell' for="selectBrakeRear">Hinterbremse:</label>
					<select id="selectBrakeRear" class="form-control priceTableCellRight cell customizingSelectBox"></select>
				</div>
				<div></div>
				<div class="row" id="totalPriceRow">
					<span class="priceTableCellLeft cell">Total:</span>
					<span class="priceTableCellRight cell"><span
							id='totalPrice'><?php echo $this->price($article->getPrice()) ?></span></span>
				</div>
				<?php
			}
			?>
		</div>
		<small>inkl. MWST.</small>
		<br>
		<label class="block showLeft" for="mengenListe">Menge: </label>
		<select id="mengenListe" class="form-control selectWidth block">
			<datalist id="amount">
				<option value="1" selected>1</option>
				<option value="2">2</option>
				<option value="3">3</option>
				<option value="4">4</option>
				<option value="5">5</option>
			</datalist>
		</select>
		<!--		</p>-->
		<button id="shoppingCartBtn" class="btn btn-default shoppingCartButton">
			<svg version="1.1" class="shoppingCartButtonPic" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
				 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
				 viewBox="0 0 446.843 446.843"
				 xml:space="preserve">
		<path d="M444.09,93.103c-2.698-3.699-7.006-5.888-11.584-5.888H109.92c-0.625,0-1.249,0.038-1.85,0.119l-13.276-38.27
		c-1.376-3.958-4.406-7.113-8.3-8.646L19.586,14.134c-7.374-2.887-15.695,0.735-18.591,8.1c-2.891,7.369,0.73,15.695,8.1,18.591
		l60.768,23.872l74.381,214.399c-3.283,1.144-6.065,3.663-7.332,7.187l-21.506,59.739c-1.318,3.663-0.775,7.733,1.468,10.916
		c2.24,3.183,5.883,5.078,9.773,5.078h11.044c-6.844,7.616-11.044,17.646-11.044,28.675c0,23.718,19.298,43.012,43.012,43.012
		s43.012-19.294,43.012-43.012c0-11.029-4.2-21.059-11.044-28.675h93.776c-6.847,7.616-11.048,17.646-11.048,28.675
		c0,23.718,19.294,43.012,43.013,43.012c23.718,0,43.012-19.294,43.012-43.012c0-11.029-4.2-21.059-11.043-28.675h13.433
		c6.599,0,11.947-5.349,11.947-11.948c0-6.599-5.349-11.947-11.947-11.947H143.647l13.319-36.996
		c1.72,0.724,3.578,1.152,5.523,1.152h210.278c6.234,0,11.751-4.027,13.65-9.959l59.739-186.387
		C447.557,101.567,446.788,96.802,444.09,93.103z M169.659,409.807c-10.543,0-19.116-8.573-19.116-19.116
		s8.573-19.117,19.116-19.117s19.116,8.574,19.116,19.117S180.202,409.807,169.659,409.807z M327.367,409.807
		c-10.543,0-19.117-8.573-19.117-19.116s8.574-19.117,19.117-19.117c10.542,0,19.116,8.574,19.116,19.117
		S337.909,409.807,327.367,409.807z M402.52,148.149h-73.161V115.89h83.499L402.52,148.149z M381.453,213.861h-52.094v-37.038
		h63.967L381.453,213.861z M234.571,213.861v-37.038h66.113v37.038H234.571z M300.684,242.538v31.064h-66.113v-31.064H300.684z
		 M139.115,176.823h66.784v37.038h-53.933L139.115,176.823z M234.571,148.149V115.89h66.113v32.259H234.571z M205.898,115.89v32.259
		h-76.734l-11.191-32.259H205.898z M161.916,242.538h43.982v31.064h-33.206L161.916,242.538z M329.359,273.603v-31.064h42.909
		l-9.955,31.064H329.359z"/>
				<span>in den Warenkorb</span>
		</button>
	</div>
</div>
<div id="detailProductDetails">
	<?php
	echo $this->ProductInfo
	?>
</div>

