<?php
/**
 * Created by PhpStorm.
 * User: Kinomi
 * Date: 28.05.2016
 * Time: 23:15
 */
?>
<div id="detailParth">
	<a href="">Startseite</a> > <a href=""></a>
</div>
<div class="detailContent flexHeader">
	<div class="detailPicture flexFillWidth" >
		<h1><?php
			/** @var \BikeStore\Model\Article $article */
				echo $article->getName();
			?>
			</h1>
		<img src="/image/<?php echo $article->getImageName()
?>"/>
	</div>
	<div id="detailBuy">
		<p>
			<b>€ <?php echo $article->getPrice()?> ,- </b><br>
			<small>inkl. MWST.</small><br>
			<form>
			<label class="block showLeft">Menge: </label>
				<select class="form-control selectWidth block">
					<datalist id="amount">
						<option value="1" selected>1</option>
						<option value="2">2</option>
						<option value="3">3</option>
						<option value="4">4</option>
						<option value="5">5</option>
					</datalist></option>
				</select>
			</form>
		</p>
		<button class="btn btn-default shoppingCartButton">
			<p>Warenkorb</p>
		</button>
	</div>
</div>
<div id="detailProductDetails">
	<?php
		echo $this->ProductInfo
	?>
</div>

