<?php
/**
 * Created by PhpStorm.
 * User: Kinomi
 * Date: 28.05.2016
 * Time: 22:08
 */
$this->headLink()->prependStylesheet($this->basePath() . '/css/boxedLayoutAnzeige.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/pageNavigator.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bikePart.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/filterForm.css');

$this->headScript()->appendFile($this->basePath() . '/js/bikePartView.js');
$this->headScript()->appendFile($this->basePath() . '/js/pageNavigator.js');
$this->headScript()->appendFile($this->basePath() . '/js/FilterForm.js');


echo "<h1>Fahrräder</h1>";

$alleElemente = array();
/** @var \BikeStore\Model\Bicycle $Eqipment */
foreach ($this->bicycles as $Eqipment)
{
	$element = (\BikeStore\Model\Manager\EquipmentManager::getAsArray($Eqipment));;
	$element["url"] = $this->url('articleDetails', array('id' => $Eqipment->getId()));
	$element["bikeType"] = \BikeStore\Model\Manager\Equipment\FrameManager::resolveBikeType($Eqipment->getFrame()->getBikeType());
	$element["weelSize"] = $Eqipment->getFrontWheel()->getSize();
	$element["frameSize"] = $Eqipment->getFrame()->getFrameSize();
	$alleElemente[] = $element;

}
$ElementArray = json_encode($alleElemente);
echo "<form name = \"test\" action=''><button id=\"list \"  class=\"btn btn-default bikeShopDefaultBtn\" type=\"button\" onclick=\"elementRender.createList()\">";
include(realpath('public/image/list.svg'));
echo "</button></br>";
echo "<button id=\"list \"  class=\"btn btn-default bikeShopDefaultBtn\" type=\"button\" onclick=\"elementRender.createBox()\">";
include (realpath('public/image/box.svg'));
echo "</button></form>";


$this->inlineScript()->captureStart();
echo <<<JS
	$(document).ready(function() {
		pageNavigator.actualPage = $this->page;
		pageNavigator.maxPage = $this->maxPage;
		elementRender.BikeList = true;
	  	elementRender.addArrayElements($ElementArray);
	  	elementRender.init();
	  	elementRender.render();
	  	
	  	FilterForm.setForm($("#bicycleFilterForm"));
		$(".sendFormOnClick").click(function(){
			FilterForm.sendForm();
		});
	})
JS;
$this->inlineScript()->captureEnd();

echo "<div class='row'>";
echo "<div class='columns small-2'>";
$this->filterForm->setAttribute("action", $this->url("bikelist"));
$this->filterForm->prepare();
echo $this->form()->openTag($this->filterForm);
echo $this->formHidden($this->filterForm->get("search"));
echo $this->formHidden($this->filterForm->get("page"));
?>

<div id='bicycleFormFrameType' class = "multiCheckBox">
	<?php
	echo $this->myForm()->multiCheckBox($this->filterForm->get("frameType"));
	?>
</div>
<br/>
<div id='bicycleFormFrameType' class = "multiCheckBox">
	<?php
	echo $this->myForm()->multiCheckBox($this->filterForm->get("riderType"));
	?>
</div>
<div id='bicycleFormFrameHeight'>
	Rahmenhöhe:
	<div class = 'row'>
		<?php
		echo "<div class = 'columns large-5 small-5'>" . $this->formRow($this->filterForm->get("frameHeightMin")) .
			 "</div>";
		echo "<div class = 'columns large-5 small-5'>" . $this->formRow($this->filterForm->get("frameHeightMax")) .
			 "</div>";
		echo "<div class = 'columns large-2 small-2'>" .
			 $this->formRow($this->filterForm->get("smallSubmitButton")) . "</div>";
		?>
	</div>
</div>
<div id='bicycleFormPrice'>
	Preis:
	<div class = 'row'>
		<?php
		echo "<div class = 'columns large-5 small-5'>" . $this->formRow($this->filterForm->get("priceMin")) .
			 "</div>";
		echo "<div class = 'columns large-5 small-5'>" . $this->formRow($this->filterForm->get("priceMax")) .
			 "</div>";
		echo "<div class = 'columns large-2 small-2'>" .
			 $this->formRow($this->filterForm->get("smallSubmitButton")) . "</div>";
		?>
	</div>
</div>
<?php
echo $this->form()->closeTag();
echo "</div>";
?>
<div class="columns large-10"><p id='AusgabePanel'></p></div>
</div>
