<?php
/**
 * Created by PhpStorm.
 * User: Kinomi
 * Date: 28.05.2016
 * Time: 22:08
 */
$this->headLink()->prependStylesheet($this->basePath() . '/css/boxedLayoutAnzeige.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/pageNavigator.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bikePart.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/filterForm.css');

$this->headScript()->appendFile($this->basePath() . '/js/bikePartView.js');
$this->headScript()->appendFile($this->basePath() . '/js/pageNavigator.js');
$this->headScript()->appendFile($this->basePath() . '/js/FilterForm.js');


echo "<h1>Fahrräder</h1>";

$alleElemente = array();
/** @var \BikeStore\Model\Bicycle $equipment */
foreach ($this->bicycles as $equipment)
{
	$element = (\BikeStore\Model\Manager\EquipmentManager::getAsArray($equipment));;
	$element["url"] = $this->url('articleDetails', array('id' => $equipment->getId()));
	$element["bikeType"] = \BikeStore\Model\Manager\Equipment\FrameManager::resolveBikeType($equipment->getFrame()->getBikeType());
	$element["weelSize"] = $equipment->getFrontWheel()->getSize();
	$element["frameSize"] = $equipment->getFrame()->getFrameSize();
	$alleElemente[] = $element;
}
$ElementArray = json_encode($alleElemente);

$this->inlineScript()->captureStart();
echo <<<JS
	$(document).ready(function() {
		pageNavigator.actualPage = $this->page;
		pageNavigator.maxPage = $this->maxPage;
		elementRender.BikeList = true;
	  	elementRender.addArrayElements($ElementArray);
	  	elementRender.init();
	  	elementRender.render();
	  	
	  	FilterForm.setForm($("#bicycleFilterForm"));
		$(".sendFormOnClick").click(function(){
			$("input[name=page]").val(1);
			FilterForm.sendForm();
		});
	})
	
	function setFilterRanges(settings) {
		var jq_minPrice = $('input[name=priceMin]'),
			jq_maxPrice = $('input[name=priceMax]'),
			jq_minFrameHeight = $('input[name=frameHeightMin]'),
			jq_maxFrameHeight = $('input[name=frameHeightMax]');
		
		if(!jq_minPrice.val())
			jq_minPrice.val(settings.minPrice).attr('min', settings.minPrice).attr('max', settings.maxPrice);
		
		if(!jq_maxPrice.val())
			jq_maxPrice.val(settings.maxPrice).attr('min', settings.minPrice).attr('max', settings.maxPrice);
			
		if(!jq_minFrameHeight.val())
			jq_minFrameHeight.val(settings.minFrameSize).attr('min', settings.minFrameSize).attr('max', settings.maxFrameSize);
			
		if(!jq_maxFrameHeight.val())
			jq_maxFrameHeight.val(settings.maxFrameSize).attr('min', settings.minFrameSize).attr('max', settings.maxFrameSize);
	}
JS;
$this->inlineScript()->captureEnd();

echo "<div class='row'>";
echo "<div class='columns small-5 medium-3 large-2'>";
$this->filterForm->setAttribute("action", $this->url("bikelist"));
$this->filterForm->prepare();

echo "<button id='list '  class='bikeShopDefaultBtn' type='button' onclick='elementRender.createList()' title='Listenansicht'>";
include(realpath('public/image/list.svg'));
echo "</button>";
echo "<button id='list '  class='bikeShopDefaultBtn' type='button' onclick='elementRender.createBox()' title='Kachelansicht'>";
include(realpath('public/image/box.svg'));
echo "</button>";

echo "<h4>Filter</h4>";

echo $this->form()->openTag($this->filterForm);
echo $this->formHidden($this->filterForm->get("search"));
echo $this->formHidden($this->filterForm->get("page"));
?>

<div id='bicycleFormFrameType' class="multiCheckBox">
	<?php
	echo $this->myForm()->multiCheckBox($this->filterForm->get("frameType"));
	?>
</div>
<br/>
<div id='bicycleFormFrameType' class="multiCheckBox">
	<?php
	echo $this->myForm()->multiCheckBox($this->filterForm->get("riderType"));
	?>
</div>
<div id='bicycleFormFrameHeight'>
	<h4>Rahmenhöhe</h4>
	<div class='row'>
		<?php
		echo "<div class = 'columns large-5 small-5'>" . $this->formRow($this->filterForm->get("frameHeightMin")) .
			 "</div>";
		echo "<div class = 'columns large-5 small-5'>" . $this->formRow($this->filterForm->get("frameHeightMax")) .
			 "</div>";
		echo "<div class = 'columns large-2 small-2'>" .
			 $this->formRow($this->filterForm->get("smallSubmitButton")) . "</div>";
		?>
	</div>
</div>
<div id='bicycleFormPrice'>
	<h4>Preis</h4>
	<div class='row'>
		<?php
		echo "<div class = 'columns large-5 small-5'>" . $this->formRow($this->filterForm->get("priceMin")) .
			 "</div>";
		echo "<div class = 'columns large-5 small-5'>" . $this->formRow($this->filterForm->get("priceMax")) .
			 "</div>";
		echo "<div class = 'columns large-2 small-2'>" .
			 $this->formRow($this->filterForm->get("smallSubmitButton")) . "</div>";
		?>
	</div>
</div>
<?php
echo $this->form()->closeTag();
echo "</div>";
?>
<div class="columns"><p id='AusgabePanel'></p></div>
</div>