<?php
$this->headLink()->prependStylesheet($this->basePath() . '/css/bikePart.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/boxedLayoutAnzeige.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/filterForm.css');
$this->headScript()->appendFile($this->basePath() . '/js/bikePartView.js');


echo "<h1>Fahrradteile</h1>";
$alleElemente = array();
foreach($this->equipments as $Eqipment)
{
	$element = (\BikeStore\Model\Manager\EquipmentManager::getAsArray($Eqipment));;
	$element["url"] = $this->url('articleDetails', array('id' => $Eqipment->getId()));
	$alleElemente[] = $element;
}
$ElementArray = json_encode($alleElemente);
echo "<form name = \"test\" action=''><button type=\"button\" onclick=\"elementRender.createList()\"> Liste </button> </br>";
echo "<button type=\"button\" onclick=\"elementRender.createBox()\"> Kacheln </button></form>";


$this->inlineScript()->captureStart();

echo <<<JS
	$(document).ready(function() {
		elementRender.BikeList = false;
	  	elementRender.addArrayElements($ElementArray);
	  	elementRender.createList();
	  	
	})
JS;


$this->inlineScript()->captureEnd();
echo "<div class='columns large-2'>";
$this->filterForm->setAttribute("action", $this->url("Bikepart"));
$this->filterForm->prepare();
echo $this->form()->openTag($this->filterForm);
echo $this->formHidden($this->filterForm->get("search"));
echo $this->formHidden($this->filterForm->get("page"));
?>

<div id = 'bikePartType'>
	<?php
		echo $this->myForm()->multiCheckBox($this->filterForm->get("equipmentTypes"));
	?>
</div>
<div id = 'bikePartFormPrice'>
	Preis:
		<div>
		<?php
			echo "<div class = 'columns large-5 small-5'>".$this->formRow($this->filterForm->get("priceMin"))."</div>";
			echo "<div class = 'columns large-5 small-5'>".$this->formRow($this->filterForm->get("priceMax"))."</div>";
			echo "<div class = 'columns large-2 small-2'>".$this->formRow($this->filterForm->get("priceSubmitButton"))."</div>";
		?>
			</div>
	</div>
<?php
echo $this->form()->closeTag();
echo "</div>";
?>
<div class="columns large-10"><p id='AusgabePanel'></p></div>


<?php


//echo "<div class = 'table maxWidth'>";
//	echo "<div class ='row'>
//			<div class = 'cell'></div>
//			<div class = 'cell'>Name</div>
//			<div class = 'cell'>Preis</div>
//		</div>";
//
//		/** @var \BikeStore\Model\Equipment $Eqipment */
//		foreach($this->equipments as $Eqipment){
////			echo "<div class = 'bikePartElement row maxWidthw'>";
//			echo '<a class = "row totalyHidden hiddenLink"  href="'.$this->url('bikelist/details', array('id' => $Eqipment->getId())).'" >';
//			echo "<div class = 'cell bikePartImg'><img class = 'bikePartImg' src='/image/".$this->escapeHtml($Eqipment->getImageName())."'></div>";
//			echo "<div class = 'bikePartInfo cell'>
//					<div class = 'bikePartName'>".$this->escapeHtml($Eqipment->getName())."</div>
//					<div>".$this->escapeHtml($Eqipment->getQuickDescription())."</div>
//				</div>";
//			echo "<div class = 'cell bikePartPrice'>".$this->escapeHtml($Eqipment->getPrice())."</div>";
//			echo '</a>';
//		//	echo "</div>";
//		}
//
//echo "</div>";
//
////echo $this->myvar;