<?php
/**
 * Created by PhpStorm.
 * User: Silas
 * Date: 25.03.2016
 * Time: 13:40
 */

namespace Application\Form;


use Application\Form\Hydrator\ChangePasswordHydrator;
use Application\Form\InputFilter\ChangePasswordInputFilter;
use Application\Model\Manager\UserManager;
use Zend\Form\Element\Hidden;
use Zend\Form\Element\Password;
use Zend\Mvc\Controller\Plugin\FlashMessenger;

class ChangePasswordForm extends MyForm{

    /** @var  UserManager */
    private $userManager;

    public function __construct(UserManager $userManager, FlashMessenger $flashMessenger = null, $name = null, $options = array())
    {
        $this->userManager = $userManager;
        parent::__construct($flashMessenger, $name, $options); // TODO: Change the autogenerated stub
    }


    public function addElements()
    {
        $oldPassword = new Password("oldPassword");
        $oldPassword->setLabel("Altes Passwort:");
        $this->add($oldPassword);

        $newPassword1 = new Password("newPassword1");
        $newPassword1->setLabel("Neues Passwort:");
        $this->add($newPassword1);

        $newPassword2 = new Password("newPassword2");
        $newPassword2->setLabel("Neues Passwort wiederholen:");
        $this->add ($newPassword2);

        $this->addSubmitButton("Speichern");
    }

    public function addEssentials()
    {
        $this->setHydrator(new ChangePasswordHydrator($this->userManager));
        $this->setInputFilter(new ChangePasswordInputFilter($this->userManager));
    }


} 