<?php
$n = 0;

echo "<div id = 'flashMessageContainer'>";
$this->inlineScript()->captureStart();
echo <<<JS
    $(document).ready(function(){
JS;
$this->flashMessenger()->setNamespace(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_SUCCESS);
foreach (array_merge($this->flashMessenger()->getMessages(), $this->flashMessenger()->getCurrentMessages()) as $message) {
    echo <<<JS
        flashMessenger.addMessage(flashMessenger.messageTypeSuccess, "$message");
JS;
}

$this->flashMessenger()->setNamespace(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_DEFAULT);
foreach (array_merge($this->flashMessenger()->getMessages(), $this->flashMessenger()->getCurrentMessages()) as $message) {
    echo <<<JS
        flashMessenger.addMessage(flashMessenger.messageTypeDefault, "$message");
JS;
}

$this->flashMessenger()->setNamespace(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_ERROR);
foreach (array_merge($this->flashMessenger()->getMessages(), $this->flashMessenger()->getCurrentMessages()) as $message) {
    echo <<<JS
        flashMessenger.addMessage(flashMessenger.messageTypeError, "$message");
JS;
}

$this->flashMessenger()->setNamespace(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_INFO);
foreach (array_merge($this->flashMessenger()->getMessages(), $this->flashMessenger()->getCurrentMessages()) as $message) {
    echo <<<JS
        flashMessenger.addMessage(flashMessenger.messageTypeInfo, "$message");
JS;
}

$this->flashMessenger()->setNamespace(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_WARNING);
foreach (array_merge($this->flashMessenger()->getMessages(), $this->flashMessenger()->getCurrentMessages()) as $message) {
    echo <<<JS
        flashMessenger.addMessage(flashMessenger.messageTypeWarning, "$message");
JS;
}

echo <<<JS
    });
JS;
$this->inlineScript()->captureEnd();
echo "</div>";

$this->flashMessenger()->clearCurrentMessagesFromContainer();
$this->flashMessenger()->clearMessagesFromContainer();