<?php
if (!isset($this->numberArticlesInShoppingCart))
{
	$this->numberArticlesInShoppingCart = 0;
}

echo $this->doctype(); ?>

<html lang="de">
<head>
	<title>Puzzles</title>
	<meta charset="utf-8">
	<?php echo $this->headTitle("Silas.link")->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() .
																											   '/image/favicon.ico'))
		->prependStylesheet($this->basePath() . '/css/myModalDialog.css')
		->prependStylesheet($this->basePath() . '/css/application.css')
		->prependStylesheet($this->basePath() . '/css/style.css')
		->prependStylesheet($this->basePath() . '/css/jquery-ui.theme.css')
		->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
		->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
		->prependStylesheet($this->basePath() . '/css/bootstrap.css')
		->prependStylesheet($this->basePath() . '/css/flashMessenger.css')
		->prependStylesheet($this->basePath() . '/css/dropit.css')
		->prependStylesheet($this->basePath() . '/css/pageNavigator.css')
		->prependStylesheet($this->basePath() . '/css/foundation.css')
		->prependStylesheet($this->basePath() . '/css/myForm.css'); ?>

	<!-- Scripts -->
	<?php echo $this->headScript()
		->prependFile($this->basePath() . '/js/MyJsonAjax.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/userManager.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/dropit.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/always.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/myForm.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/settings.js')
		->prependFile($this->basePath() . '/js/myDialog.js')
		->prependFile($this->basePath() . '/js/jquery.confirm.min.js')
		->appendFile($this->basePath() . '/js/bootstrap.min.js')
		->prependFile($this->basePath() . '/js/jquery-ui.js')
		->prependFile($this->basePath() . '/js/jquery.min.js')
		->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		->prependFile($this->basePath() . '/js/flashMessenger.js', 'text/javascript')
		->appendFile($this->basePath() . '/js/foundation.js', 'text/javascript')
		->appendFile($this->basePath() . '/js/helper.js', 'text/javascript');

	$basePath = $this->basePath();
	$this->inlineScript()->captureStart();
	$stuff = $this->numberArticlesInShoppingCart;
	$searchStringValue = (isset($searchString))?$searchString:"";
	echo <<<JS
		settings.basePath = '$basePath';
		numberArticlesInShoppingCart = $stuff;
		
		$(document).ready(function(){
			$("svg circle").click(function() {
				$("body").addClass('ya-see-me-rolling');
				return false;
			});
			$("#searchForm").submit(function(e){
				if (FilterForm.hasForm())
				{
					e.preventDefault();
					FilterForm.setSearch($(this).find(".suchleiste").val());
					FilterForm.sendForm();
				}
			});
			
			$(".amountInput").autocomplete({
				minLength:0,
				source: [
				"1",
				"2",
				"3",
				"4",
				"5",
				"10",
				"15",
				]
			}).click(function(){            
				$(this).autocomplete("search", "")
				// $(this).data("autocomplete").search($(this).val());
			});
		})
JS;

	$this->inlineScript()->captureEnd();
	?>

</head>
<body>
	<nav class="navbar  navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar">X</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse">
				<?php
				echo $this->navigation('navigation')->menu()->setUlClass("nav navbar-nav default");
				?>
			</div>
		</div>
	</nav>
	<div class="myMainContainerWrapper">
		<div class="container">
			<?php include("alerts.phtml"); ?>
			<div id="header" class="header row align-middle">
				<div id="logo" class="columns show-for-large shrink">
					<a href="<?php echo $this->url("home"); ?>" class="totallyHidden">
						<div class='bikeStoreLogo'>
							<?php include(realpath('public/image/wheel.svg')) ?>
						</div>
						<div id="logoLabel">Puzzles</div>
					</a>
				</div>
				<div id="search" class="columns expand">
					<form class="flexHeader" id='searchForm' action="<?php echo $this->url("search"); ?>" method="GET">
						<div class="flexFillWidth">
							<input name="search" class="suchleiste flexFillWidth form-control" type="text"
								   placeholder=" Suche..." value = "<?php echo $searchStringValue ?>" />
						</div>
						<div>
							<button class="sucheButton btn">
								<?php include(realpath('public/image/search.svg')) ?>
							</button>
						</div>
					</form>
				</div>
				<div id="shoppingCart" class="columns small-12 large-3">
					<a href="<?php echo $this->url("shoppingCart"); ?>">
						<div class="warenkorbAlgemein">
							<div class="warenkorbPic">
								<?php include(realpath('public/image/shoppingcart.svg')) ?>
							</div>
							<span id="warenkorbText"><?php echo $this->numberArticlesInShoppingCart ?> Artikel <br
									class="show-for-large"> im Warenkorb</span>
						</div>
					</a>
				</div>
			</div>
			<nav class="mainnav">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar">X</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse">
					<?php
					echo $this->navigation('mainNavigation')->menu()->setUlClass("nav navbar-nav mainNavigation");
					?>
				</div>
			</nav>
			<div class="mainContent">
				<?php
				echo $this->content;
				?>
				<?php echo $this->inlineScript() ?>
			</div>
		</div>
	</div>
	<footer>
		<small>
			<a href="<?php echo $this->url("showImprint"); ?>">Impressum</a> -
			<a href="<?php echo $this->url("showPrivacyPolicy"); ?>">Datenschutzbestimmungen</a> -
			<a href="<?php echo $this->url("showAgb"); ?>">AGB</a>
		</small>
	</footer>
</body>
</html>
