<?php
if (!isset($this->numberArticlesInShoppingCart))
{
	$this->numberArticlesInShoppingCart = 0;
}

echo $this->doctype(); ?>

<html lang="de">
<head>
	<title>Puzzles</title>
	<meta charset="utf-8">
	<?php echo $this->headTitle("Silas.link")->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() .
																											   '/image/favicon.ico'))
		->prependStylesheet($this->basePath() . '/css/myModalDialog.css')
		->prependStylesheet($this->basePath() . '/css/application.css')
		->prependStylesheet($this->basePath() . '/css/style.css')
		->prependStylesheet($this->basePath() . '/css/jquery-ui.theme.css')
		->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
		->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
		->prependStylesheet($this->basePath() . '/css/bootstrap.css')
		->prependStylesheet($this->basePath() . '/css/flashMessenger.css')
		->prependStylesheet($this->basePath() . '/css/dropit.css')
		->prependStylesheet($this->basePath() . '/css/foundation.css')
		->prependStylesheet($this->basePath() . '/css/myForm.css'); ?>

	<!-- Scripts -->
	<?php echo $this->headScript()
		->prependFile($this->basePath() . '/js/MyJsonAjax.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/userManager.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/dropit.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/always.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/myForm.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/settings.js')
		->prependFile($this->basePath() . '/js/myDialog.js')
		->prependFile($this->basePath() . '/js/jquery.confirm.min.js')
		->appendFile($this->basePath() . '/js/bootstrap.min.js')
		->prependFile($this->basePath() . '/js/jquery-ui.js')
		->prependFile($this->basePath() . '/js/jquery.min.js')
		->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		->appendFile($this->basePath() . '/js/foundation.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/flashMessenger.js', 'text/javascript');

	$basePath = $this->basePath();
	$this->inlineScript()->captureStart();
	$stuff = $this->numberArticlesInShoppingCart;
	echo <<<JS
		settings.basePath = '$basePath';
		numberArticlesInShoppingCart = $stuff;
		
		$("svg circle").click(function() {
			$("body").addClass('ya-see-me-rolling');
			return false;
		});
JS;

	$this->inlineScript()->captureEnd();
	?>

</head>
<body>
	<nav class="navbar  navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar">X</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse">
				<?php
				echo $this->navigation('navigation')->menu()->setUlClass("nav navbar-nav default");
				?>
			</div>
		</div>
	</nav>
	<div class="myMainContainerWrapper">
		<div class="container">
			<?php include("alerts.phtml"); ?>
			<div id="header" class="header flexHeader">
				<div class="logo">
					<a href="<?php echo $this->url("home"); ?>" class="totallyHidden">
						<div class='bikeStoreLogo'>
							<?php include(realpath('public/image/wheel.svg')) ?>
						</div>
						<div id="logoLabel">Puzzles</div>
					</a>
				</div>
				<div class="suche flexFillWidth">
					<div class="flexHeader">
						<div class="flexFillWidth">
							<input class="suchleiste flexFillWidth form-control" type="text" placeholder=" Suche..."/>
						</div>
						<div>
							<button class="sucheButton btn">
								<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 57 57">
									<path d="M55 52L41.7 37.7C45 33.7 47 28.4 47 23 47 10.3 36.7 0 24 0S1 10.3 1 23s10.3 23 23 23c4.7 0 9.3-1.4 13.2-4.2L50.8 56c.6.6 1.4 1 2.2 1 .8 0 1.5-.3 2-1 1.3-1 1.3-3 0-4zM24 6c9.4 0 17 7.6 17 17s-7.6 17-17 17S7 32.4 7 23 14.6 6 24 6z"/>
								</svg>
							</button>
						</div>

					</div>
				</div>
				<div class="warenkorb">
					<a href="<?php echo $this->url("shoppingCart"); ?>">
						<div class="warenkorbAlgemein">
							<div class="warenkorbPic"><svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
														   viewBox="0 0 446.843 446.843"
														   xml:space="preserve">
														<path d="M444.09,93.103c-2.698-3.699-7.006-5.888-11.584-5.888H109.92c-0.625,0-1.249,0.038-1.85,0.119l-13.276-38.27
															c-1.376-3.958-4.406-7.113-8.3-8.646L19.586,14.134c-7.374-2.887-15.695,0.735-18.591,8.1c-2.891,7.369,0.73,15.695,8.1,18.591
															l60.768,23.872l74.381,214.399c-3.283,1.144-6.065,3.663-7.332,7.187l-21.506,59.739c-1.318,3.663-0.775,7.733,1.468,10.916
															c2.24,3.183,5.883,5.078,9.773,5.078h11.044c-6.844,7.616-11.044,17.646-11.044,28.675c0,23.718,19.298,43.012,43.012,43.012
															s43.012-19.294,43.012-43.012c0-11.029-4.2-21.059-11.044-28.675h93.776c-6.847,7.616-11.048,17.646-11.048,28.675
															c0,23.718,19.294,43.012,43.013,43.012c23.718,0,43.012-19.294,43.012-43.012c0-11.029-4.2-21.059-11.043-28.675h13.433
															c6.599,0,11.947-5.349,11.947-11.948c0-6.599-5.349-11.947-11.947-11.947H143.647l13.319-36.996
															c1.72,0.724,3.578,1.152,5.523,1.152h210.278c6.234,0,11.751-4.027,13.65-9.959l59.739-186.387
															C447.557,101.567,446.788,96.802,444.09,93.103z M169.659,409.807c-10.543,0-19.116-8.573-19.116-19.116
															s8.573-19.117,19.116-19.117s19.116,8.574,19.116,19.117S180.202,409.807,169.659,409.807z M327.367,409.807
															c-10.543,0-19.117-8.573-19.117-19.116s8.574-19.117,19.117-19.117c10.542,0,19.116,8.574,19.116,19.117
															S337.909,409.807,327.367,409.807z M402.52,148.149h-73.161V115.89h83.499L402.52,148.149z M381.453,213.861h-52.094v-37.038
															h63.967L381.453,213.861z M234.571,213.861v-37.038h66.113v37.038H234.571z M300.684,242.538v31.064h-66.113v-31.064H300.684z
															 M139.115,176.823h66.784v37.038h-53.933L139.115,176.823z M234.571,148.149V115.89h66.113v32.259H234.571z M205.898,115.89v32.259
															h-76.734l-11.191-32.259H205.898z M161.916,242.538h43.982v31.064h-33.206L161.916,242.538z M329.359,273.603v-31.064h42.909
															l-9.955,31.064H329.359z"/></div>
							<div class="warenkorbText"><?php echo $this->numberArticlesInShoppingCart ?> Artikel <br> im Warenkorb</div>
						</div>
					</a>
				</div>
			</div>
			<nav class="mainnav">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar">X</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse">
					<?php
					echo $this->navigation('mainNavigation')->menu()->setUlClass("nav navbar-nav mainNavigation");
					?>
				</div>
			</nav>
			<div class="mainContent">
				<?php

				echo $this->content;

				?>
				<?php echo $this->inlineScript() ?>
			</div>
		</div>
	</div>
	<footer>
		<small>
			<a href="<?php echo $this->url("showImprint"); ?>">Impressum</a> -
			<a href="<?php echo $this->url("showPrivacyPolicy"); ?>">Datenschutzbestimmungen</a> -
			<a href="<?php echo $this->url("showAgb"); ?>">AGB</a>
		</small>
	</footer>
</body>
</html>
