<?php
echo $this->doctype(); ?>

<html lang="de">
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle("Silas.link")->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() .
																											   '/img/logo.ico'))
		->prependStylesheet($this->basePath() . '/css/myModalDialog.css')
		->prependStylesheet($this->basePath() . '/css/application.css')
		->prependStylesheet($this->basePath() . '/css/style.css')
		->prependStylesheet($this->basePath() . '/css/jquery-ui.theme.css')
		->prependStylesheet($this->basePath() . '/css/jquery-ui.css')
		->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
		->prependStylesheet($this->basePath() . '/css/bootstrap.css')
		->prependStylesheet($this->basePath() . '/css/flashMessenger.css')
		->prependStylesheet($this->basePath() . '/css/dropit.css')
		->prependStylesheet($this->basePath() . '/css/myForm.css'); ?>

	<!-- Scripts -->
	<?php echo $this->headScript()
		->prependFile($this->basePath() . '/js/MyJsonAjax.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/userManager.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/dropit.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/always.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/myForm.js', 'text/javascript')
		->prependFile($this->basePath() . '/js/settings.js')
		->prependFile($this->basePath() . '/js/myDialog.js')
		->prependFile($this->basePath() . '/js/jquery.confirm.min.js')
		->prependFile($this->basePath() . '/js/bootstrap.min.js')
		->prependFile($this->basePath() . '/js/jquery-ui.js')
		->prependFile($this->basePath() . '/js/jquery.min.js')
		->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
		->prependFile($this->basePath() . '/js/flashMessenger.js', 'text/javascript');

	$basePath = $this->basePath();
	$this->inlineScript()->captureStart();
	echo <<<JS
		settings.basePath = '$basePath';
JS;

	$this->inlineScript()->captureEnd();
	?>

</head>
<body>
	<nav class="navbar  navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar">X</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse">
				<?php
				echo $this->navigation('navigation')->menu()->setUlClass("nav navbar-nav");
				?>
			</div>
		</div>
	</nav>
	<div class="myMainContainerWrapper">
		<div class="container">
			<div class="header flexHeader">
				<div class="logo">
					<p>Hier fehlt ein Logo</p>
				</div>
				<div class="suche flexFillWidth">
					<div class="flexHeader">
						<div class="flexFillWidth">
							<input class="suchleiste flexFillWidth" type="text" value="Suche..."/>
						</div>
						<div>
							<button class="sucheButton"><img class="suchePic" src="image/Lupe_grau.png"/></button>
						</div>

					</div>
				</div>
				<div class="warenkorb">
					<a href=" ">0 Artikel im Warenkorb</a>
				</div>
			</div>
			<nav class="mainnav">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar">X</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse">
					<?php
					echo $this->navigation('mainNavigation')->menu()->setUlClass("nav navbar-nav");
					?>
				</div>
			</nav>
			<div class="mainContent">
				<?php

				include("alerts.phtml");
				echo $this->content;

				?>
				<?php echo $this->inlineScript() ?>
			</div>
		</div>
	</div>
	<footer>
		<small>
			<a href="<?php echo $this->url("showImprint"); ?>">Impressum</a> -
			<a href="<?php echo $this->url("showPrivacyPolicy"); ?>">Datenschutzbestimmungen</a> -
			<a href="<?php echo $this->url("showAgb"); ?>">AGB</a>
		</small>
	</footer>
</body>
</html>
