<?php
$title = "Login";
$this->headTitle($title);

$this->form->setAttribute("action", $this->url("login", array("followTarget" => $this->followTarget)));
echo "<div class = 'columns large-6 medium-9 small-12'>";
echo "<h1>".$title."</h1>";
echo $this->myForm($this->form);
?>

<i>Achtung, ich verwende Cookies für den automatischen Login!</i>
<br/>
<a href = '<?php echo $this->url('newPassword'); ?>'>Passwort vergessen</a>
</div>