<?php

$title = "Passwort vergessen";
$this->headTitle($title);
echo "<div class = 'columns large-6'>";
echo "<h1>Passwort vergessen</h1>";
?>

<br/>
<p>	Um ein neues Passwort zu setzen, tragen Sie bitte Ihre Email ein. Wir senden Ihnen dann einen Link zu, mit dem Sie Ihr Passwort ändern können.

	<!--				Es sieht so aus, als hättest du dein Passwort vergessen...-->
	<!--				Naja, du kennst das ja schon...-->
	<!--				Trage einfach deine Email ein und wir senden dir eine Email zu.-->
	<!--                Natürlich nur, wenn du auch schon einen Account hast. Mit der-->
	<!--				Mail kannst du dir ein neues Passwort setzten. Vergiss aber-->
	<!--				nicht (so wie dein Passwort) deinen Spam-Filter zu überprüfen!-->
</p>

	<?php
	echo $this->myForm($this->form, 1, "inline")."</div>";
	?>





