<?php

$title = "Passwort vergessen";
$this->headTitle($title);
echo "<h1>Nicht schon wieder...</h1>";
?>

<br/>
<table>
	<tr>
		<td width = '33%'>
			<p>Es sieht so aus, als hättest du dein Passwort vergessen...
				Naja, du kennst das ja schon...
				Trage einfach deine Email ein und wir senden dir eine Email zu.
                Natürlich nur, wenn du auch schon einen Account hast. Mit der
				Mail kannst du dir ein neues Passwort setzten. Vergiss aber
				nicht (so wie dein Passwort) deinen Spam-Filter zu überprüfen!
			</p>
		</td>
		<td style = 'text-align:center'>
			<img alt = '*trauriges Passwort*' style = "width:70%" src="http://previews.123rf.com/images/yayayoy/yayayoy1403/yayayoy140300005/27517277-sad-emoticon-wiping-tear-smiley-face-sad.jpg">
		</td>
		<td width = '30%'>
			<p> <-- Dein Passwort, du solltest dich echt bei ihm entschuldigen...</p>
		</td>
	</tr>
</table>

<table class='nolines'>
	<?php
	echo $this->myForm($this->form, 1, "inline");
	?>
</table>





