<?php
$this->headLink()->prependStylesheet($this->basepath() . '/css/shopping-cart.css');
	?>


<!--Tabellenkopf-->
<div class="flexHeader">
	<div class="flexFillWidth">
		<h1>Warenkorb</h1>
		<div class="cartHeadline">
			Menge
		</div>
		<div class="cartHeadline">
			Preis
		</div>
		<br/>

		
<!--for-Schleife für Warenausgabe-->
	<?php
 	$numberArticles = count($this->articles);
	for ($i=0; $i<$numberArticles; $i++)
	{
		$article = $this->articles[$i]["article"];
		$number = $this->articles[$i]["count"];
//		echo "<p> <IMG SRC = \"/image/"  . $article->getImageName() . "\"/> </p>";
//		echo "<h2>" . $article->getName() . "</h2>";
//		echo "<p>" . $article->getQuickDescription() . "</p>";
//		echo "<p> <b>" . $article->getPrice() . "</b>";
//		echo "<p> $number </p>";

		?>


<!--	Eintrag in Korb mit Abgrenzung-->
		<div class="partWareWhole <?php echo ($i > 0)?"borderTop":"firstLine";?>">
<!--		Box für Bild-->
			<div class="partWareLeft">
				<img src = "/image/<?php echo $article->getImageName() ?>"/>
			</div>
<!--		Box für Produktinfo	-->
			<div class="partWareMiddle">
				<p>
				<b><?php echo $article->getName()?></b>
				<br><?php echo $article->getQuickDescription()?>
				<br>Preis pro Artikel: <b><?php echo number_format($article->getPrice(),2, ",", ".");?> €</b>
				</p>
			</div>
<!--		Box für Aanzahl	-->
			<div class="partWareRight">
				<?php echo $number?>
			</div>
<!--		Box für Preis aller Artikel eines Typs	-->
			<div class="partWareRight">
				<b><?php echo number_format(($article->getPrice()*$number),2, ",", ".")?> €</b>
			</div>
		</div>
		<?php
	}
	?>
		<div class="lastLine">
			<?php
	//		Berechnung Gesamtsumme + Gesamtanzahl Artikel
			$numberArticles = count($this->articles);
			$sum=0.00;
			$allArticles=0;
			for ($i=0; $i<$numberArticles; $i++)
			{
				/** @var \BikeStore\Model\Article $article */
				$article = $this->articles[$i]["article"];
				$number = $this->articles[$i]["count"];
				$zwischenwertSum = ($article->getPrice()*$number);
				$sum = $sum + $zwischenwertSum;
				$allArticles = $allArticles + $number;

			}
			?>


			<b>Summe (<?php echo $allArticles?> Artikel): <span class="priceColor"><?php echo number_format($sum,2, ",", ".");?> €</span></b>
		</div>
	</div>


<!--Kauf-Box rechts-->
	<div class="partBuy">



<!--		<p>Summe: <b> --><?php //echo number_format($sum,2, ",", ".");?><!-- €</b><br>-->
		<p><b>Summe: <span class="priceColor"><?php echo number_format($sum,2, ",", ".");?> €</span></b>

<!--	Kauf-Button	-->
		<br>Kaufen</p>
	</div>
</div>


