<?php
$this->headLink()->prependStylesheet($this->basepath() . '/css/shopping-cart.css');
	?>


<!--Tabellenkopf-->
<div class="flexHeader">
	<div class="flexFillWidth">
		<h1>Warenkorb</h1>
		<div class="cartHeadline">
			Menge
		</div>
		<div class="cartHeadline">
			Preis
		</div>
		<br/>

		
<!--for-Schleife für Warenausgabe-->
	<?php
	$sum=0.00;
	$allArticles=0;

	foreach ($this->articles as $articleArray)
	{
		$article = $articleArray["article"];
		$number = $articleArray["count"];
//		echo "<p> <IMG SRC = \"/image/"  . $article->getImageName() . "\"/> </p>";
//		echo "<h2>" . $article->getName() . "</h2>";
//		echo "<p>" . $article->getQuickDescription() . "</p>";
//		echo "<p> <b>" . $article->getPrice() . "</b>";
//		echo "<p> $number </p>";

		//	Berechnung Gesamtsumme + Gesamtanzahl Artikel
		$zwischenwertSum = ($article->getPrice()*$number);
		$sum = $sum + $zwischenwertSum;
		$allArticles = $allArticles + $number;
		?>


<!--	Eintrag in Korb mit Abgrenzung-->
		<div class="partWareWhole <?php echo ($allArticles > 0)?"borderTop":"firstLine";?>">
<!--		Box für Bild-->
			<div class="partWareLeft">
				<img src = "/image/<?php echo $article->getImageName() ?>"/>
			</div>
<!--		Box für Produktinfo	-->
			<div class="partWareMiddle">
				<p>
				<b><?php echo $article->getName()?></b>
				<br><?php echo $article->getQuickDescription()?>
				<br>Preis pro Artikel: <b><?php echo number_format($article->getPrice(),2, ",", ".");?> €</b>
				</p>
			</div>
<!--		Box für Aanzahl	-->
			<div class="partWareRight">
				<?php echo $number?>
			</div>
<!--		Box für Preis aller Artikel eines Typs	-->
			<div class="partWareRight">
				<b><?php echo number_format(($article->getPrice()*$number),2, ",", ".")?> €</b>
			</div>
		</div>
		<?php
	}
	?>
		<div class="lastLine">
			<b>Summe (<?php echo $allArticles?> Artikel): <span class="priceColor"><?php echo number_format($sum,2, ",", ".");?> €</span></b>
		</div>
	</div>


<!--Kauf-Box rechts-->
	<div class="partBuy">



<!--		<p>Summe: <b> --><?php //echo number_format($sum,2, ",", ".");?><!-- €</b><br>-->
		<p><b>Summe (<?php echo $allArticles?> Artikel): <span class="priceColor"><?php echo number_format($sum,2, ",", ".");?> €</span></b>

<!--	Kauf-Button	-->
		<br><br><a class="btn btn-default buyButton">Zur Kasse gehen</a></p>
	</div>
</div>


