<?php
/**
 * Created by PhpStorm.
 * User: Silas
 * Date: 01.09.2015
 * Time: 09:23
 */

namespace Application\Model\Datatable\Column;

class DialogRouteColumn extends RouteColumn
{

	private $title;
	private $buttonText;

	public function __construct($name = "", $options = array())
	{
		$this->title = "";
		$this->buttonText = "";

		parent::__construct($name, $options);
		$this->setOptions($options);
	}

	public function buildJsArray()
	{
		$array = parent::buildJsArray(); // TODO: Change the autogenerated stub

		$label = $this->getRouteLabel();
		$title = $this->getTitle();
		$buttonText = $this->getButtonText();

		$array["mRender"] = <<<JS
	function(url, type, full) {
		return '<a class = "btn btn-xs btn-default" >$label</a>';
	}
JS;
		$array["fnCreatedCell"] = <<<JS
                function(nTd, sData, oData, iRow, iCol)
                {
                    $(nTd).first().click(function(){
                        myDialog.ajaxDialog("$title", sData, "$buttonText");
                    });
                }
JS;
		return $array;
	}


	public function setOptions(array $options)
	{
		parent::setOptions($options);

		isset($options["title"]) && $this->setTitle($options["title"]);
		isset($options["buttonText"]) && $this->setButtonText($options["buttonText"]);
	}


	/**
	 * @return mixed
	 */
	public function getButtonText()
	{
		return $this->buttonText;
	}

	/**
	 * @param mixed $buttonText
	 */
	public function setButtonText($buttonText)
	{
		$this->buttonText = $buttonText;
	}

	/**
	 * @return mixed
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * @param mixed $title
	 */
	public function setTitle($title)
	{
		$this->title = $title;
	}
} 