<?php
/**
 * Created by PhpStorm.
 * User: Silas
 * Date: 19.09.2015
 * Time: 17:15
 */

namespace Application\Model\Datatable\Column;


class EnumColumn extends Column{
    /** @var  array */
    private $enumeration;

    public function __construct($name = "", $options = array())
    {
        parent::__construct($name, $options); // TODO: Change the autogenerated stub
    }

    public function setOptions(array $options)
    {
        parent::setOptions($options); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    public function getEnumeration()
    {
        return $this->enumeration;
    }

    /**
     * @param array $enumeration
     */
    public function setEnumeration($enumeration)
    {
        $this->enumeration = $enumeration;
    }

    public function addEnumeration($value, $enum)
    {
        $this->enumeration[$value] = $enum;
    }

    public function getEnum($value)
    {
        if (isset($this->enumeration[$value]))
        {
            return $this->enumeration[$value];
        }
        else
        {
            return $value;
        }
    }

    public function buildCell($row, $index)
    {
        $row[$this->getName()] = $this->getEnum($row[$this->getName()]);
        return parent::buildCell($row, $index); // TODO: Change the autogenerated stub
    }


} 